deepseek:
  api_key: "your_deepseek_api_key"
  base_url: "https://api.deepseek.com"
  ai_model_id: "deepseek-chat"

openrouter:
  api_key: "your_openrouter_api_key"
  base_url: "https://openrouter.ai/api/v1"
  ai_model_id: "openrouter/optimus-alpha"

google:
  api_key: "your_gemini_api_key"
  ai_model_id: "gemini-2.0-flash"

openai:
  api_key: "your_api_key"
  base_url: "https://api.openai.com/v1"
  ai_model_id: "gpt-4.1"
